# Generated by Django 5.0.6 on 2024-06-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Narrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_captura', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_01', models.CharField(max_length=60)),
                ('tamanho_02', models.CharField(max_length=60, null=True)),
                ('categoria_01', models.CharField(max_length=60)),
                ('categoria_02', models.CharField(max_length=60, null=True)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='GolpesNaturais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucao', models.CharField(max_length=60)),
                ('golpe_01', models.CharField(max_length=60)),
                ('golpe_02', models.CharField(max_length=60, null=True)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Deslocamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrestre', models.IntegerField(null=True)),
                ('escavacao', models.IntegerField(null=True)),
                ('natacao', models.IntegerField(null=True)),
                ('subaquatico', models.IntegerField(null=True)),
                ('voo', models.IntegerField(null=True)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Comportamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta_01', models.CharField(max_length=60)),
                ('dieta_02', models.CharField(max_length=60, null=True)),
                ('habitat_01', models.CharField(max_length=60)),
                ('habitat_02', models.CharField(max_length=60, null=True)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Capacidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('salto', models.IntegerField()),
                ('outras', models.CharField(max_length=30)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='AtributosBasais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atributo', models.CharField(max_length=60)),
                ('nome_pokemon_01', models.CharField(max_length=60)),
                ('nome_pokemon_02', models.CharField(max_length=60, null=True)),
                ('atributo_01', models.IntegerField()),
                ('atributo_02', models.IntegerField(null=True)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Procriacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=60)),
                ('grupo_reprodutivo', models.CharField(max_length=60)),
                ('incubacao', models.CharField(max_length=60)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='TiposHabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_01', models.ImageField(upload_to=None)),
                ('tipo_02', models.ImageField(null=True, upload_to=None)),
                ('habilidade_01', models.CharField(max_length=60)),
                ('habilidade_02', models.CharField(max_length=60, null=True)),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokemon')),
            ],
        ),
    ]
