# Generated by Django 5.0.6 on 2024-06-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='nome',
            new_name='nome_pokemon',
        ),
    ]
