# Generated by Django 5.0.6 on 2024-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nome_pokemon_nome_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='imagem',
            field=models.BinaryField(),
        ),
    ]
