# Generated by Django 5.0.6 on 2024-06-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_habilidade_02_tiposhabilidades_alta_habilidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidas',
            old_name='categoria_01',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='medidas',
            old_name='tamanho_01',
            new_name='tamanho',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='categoria_02',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='tamanho_02',
        ),
    ]
