# Generated by Django 5.0.6 on 2024-06-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_golpe_02_golpesnaturais_golpe_herdado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comportamento',
            old_name='dieta_02',
            new_name='dieta',
        ),
        migrations.RenameField(
            model_name='comportamento',
            old_name='habitat_02',
            new_name='habitat',
        ),
        migrations.RemoveField(
            model_name='comportamento',
            name='dieta_01',
        ),
        migrations.RemoveField(
            model_name='comportamento',
            name='habitat_01',
        ),
    ]
