# Generated by Django 5.0.6 on 2024-06-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_dieta_02_comportamento_dieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
