# Generated by Django 5.0.6 on 2024-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pokemon_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributosbasais',
            name='ataque',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='atributosbasais',
            name='ataque_especial',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='atributosbasais',
            name='defesa',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='atributosbasais',
            name='defesa_especial',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='atributosbasais',
            name='saude',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='atributosbasais',
            name='velocidade',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='capacidades',
            name='outras',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='dieta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='habitat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deslocamento',
            name='deslocamentos',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='golpesnaturais',
            name='golpe_herdado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='golpesnaturais',
            name='golpe_natural',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='tamanho',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='nome_pokemon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procriacao',
            name='grupo_reprodutivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procriacao',
            name='incubacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procriacao',
            name='sexo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='alta_habilidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='habilidade',
            field=models.CharField(max_length=100),
        ),
    ]
