# Generated by Django 5.0.6 on 2024-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_golpesnaturais_golpe_herdado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposhabilidades',
            name='tipo_02_img',
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='tipo_01_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
