# Generated by Django 5.0.6 on 2024-06-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_atributosbasais_ataque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golpesnaturais',
            name='golpe_herdado',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
