# Generated by Django 5.0.6 on 2024-06-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_golpesnaturais_golpe_herdado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidades',
            name='outras',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='dieta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='habitat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deslocamento',
            name='deslocamentos',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='golpesnaturais',
            name='golpe_natural',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='tamanho',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='procriacao',
            name='grupo_reprodutivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='procriacao',
            name='incubacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='procriacao',
            name='sexo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='alta_habilidade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='habilidade',
            field=models.CharField(max_length=200),
        ),
    ]
