# Generated by Django 5.0.6 on 2024-06-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_capacidades_outras_alter_comportamento_dieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='nome_pokemon',
            field=models.CharField(max_length=200),
        ),
    ]
