# Generated by Django 5.0.6 on 2024-06-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pokemon_nome_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='tipo_01_img',
            field=models.ImageField(max_length=300, upload_to='tipos_images/'),
        ),
    ]
