# Generated by Django 5.0.6 on 2024-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pokemon_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposhabilidades',
            name='tipo_02_img',
            field=models.ImageField(default='N/A', max_length=300, upload_to='tipos_images/'),
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='tipo_01_img',
            field=models.ImageField(default='N/A', max_length=300, upload_to='tipos_images/'),
        ),
    ]
