# Generated by Django 5.0.6 on 2024-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tiposhabilidades_tipo_02_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='tipo_01_img',
            field=models.ImageField(default='N/A', max_length=300, null=True, upload_to='tipos_images/'),
        ),
        migrations.AlterField(
            model_name='tiposhabilidades',
            name='tipo_02_img',
            field=models.ImageField(default='N/A', max_length=300, null=True, upload_to='tipos_images/'),
        ),
    ]
